[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
test_build_src = yes
lib_deps =
  h2zero/NimBLE-Arduino @ ^2.3.6

[env:native]
platform = native
build_flags =
  -std=c++17
build_src_filter =
test_build_src = yes
test_framework = unity
